### ISSUE TITLE
Robot status page shows message "Bot test page wasn't returned" after clicking "Auto create bot".

### ISSUE THREAD

**Issue by suankan** [central-queensland-uni/moodle-local_linkchecker_robot#10]
Robot status page calls function is_bot_valid() which calls URL like http://cqu.ubox001.com/local/linkchecker_robot/tests/test1.php. 
Then it attempts to find string like "Hello robot: 'moodlebot'" among the obtained HTML. Where "moodlebot" is a user created for robot on the step of installing/configuring the plugin.

[See the code](https://github.com/central-queensland-uni/moodle-local_linkchecker_robot/blob/305aa35330604aff58f040db47c286af3fd5ea53/classes/robot/crawler.php#L82-85)

However local/linkchecker_robot/tests/test1.php returns string "Hello robot: '$USER->username'" where username belongs to the user being logged in at the moment, such as admin.

[See the code](https://github.com/central-queensland-uni/moodle-local_linkchecker_robot/blob/2b9c380a83436ebe32a22aeefa8ca940e9266bc1/tests/test1.php#L40)

This seems to be causing message "Bot test page wasn't returned" to be constantly shown after we clicked "Auto create bot".

**Comment by suankan** [comment]
Fixed by adding a random hash into the test1.php output and the same hash into the is_bot_valid() HTML parser to look for. 

[commit](https://github.com/central-queensland-uni/moodle-local_linkchecker_robot/commit/90e7742d8b60fc9d68af667ec7482cda08c355f2)

**Comment by brendanheywood** [comment]
This is wrong, can you please revert this and come talk to me

**Comment by suankan** [comment]
I've reverted my commit.
Now this issue needs investigation.

**Comment by suankan** [comment]
Sorry, this was an invalid issue. 
The actual reason turned out to be a [missing space](https://github.com/central-queensland-uni/moodle-local_linkchecker_robot/blob/7c649dba1735d4aae811e108bd1dcf137230df35/classes/robot/crawler.php#L82)
Fixed by [commit](https://github.com/central-queensland-uni/moodle-local_linkchecker_robot/commit/37ccaf9b1f1614f4239c7ec693218e5df5b7c0cb)
