### ISSUE TITLE
Inconsistency in the number of broken links found

### ISSUE THREAD

**Issue by mudrd8mz** [central-queensland-uni/moodle-local_linkchecker_robot#2]
My "Robot status" page reports 2 broken links found:

![screenshot_2016-03-30_16-27-03](https://cloud.githubusercontent.com/assets/85831/14145502/70b6e314-f694-11e5-968e-0b7f88808555.png)

However, clicking the "2" link takes me to the page where 4 broken links are reported:

![screenshot_2016-03-30_16-27-23](https://cloud.githubusercontent.com/assets/85831/14145510/7949b4c0-f694-11e5-84f7-112e85d1a21c.png)

I assume the numbers should match.

**Comment by brendanheywood** [comment]
Note to self: This one is more of a language tweak, there are 2 broken pages with 4 incoming bad links

**Comment by suankan** [comment]
After discussion with Brendan it was decided to rename existing line "Broken links" on "Robot status" page to "Broken links / Unique broken URLs" and to show link of numbers like " 5 / 1".

**Comment by suankan** [comment]
Table item "Broken links" was renamed to "Broken links / URLs". It will be pointing to the same page. The right side was re-done to show 2-in-1 broken pages and unique broken URLs.

![image](https://cloud.githubusercontent.com/assets/5026704/14808465/b6a756a8-0bc8-11e6-830b-57c385dfb228.png)
