### ISSUE TITLE
Function name prefixes

### ISSUE THREAD

**Issue by mudrd8mz** [central-queensland-uni/moodle-local_linkchecker_robot#3]
Even for "local" functions such as `http_code()` in the report.php file, it would be best to follow the policy and let them have proper frankenstyle prefix to avoid potential collisions.

**Comment by suankan** [comment]
Such functions could be found by:
`
$ grep --color=auto -Prn '^function (?!local_).*' local/linkchecker_robot/*
local/linkchecker_robot/db/upgrade.php:32:function xmldb_local_linkchecker_robot_upgrade($oldversion) {
local/linkchecker_robot/extlib/simple_html_dom.php:70:function file_get_html($url, $use_include_path = false, $context=null, $offset = -1, $maxLen=-1, $lowercase = true, $forceTagsClosed=true, $target_charset = DEFAULT_TARGET_CHARSET, $stripRN=true, $defaultBRText=DEFAULT_BR_TEXT, $defaultSpanText=DEFAULT_SPAN_TEXT)
local/linkchecker_robot/extlib/simple_html_dom.php:88:function str_get_html($str, $lowercase=true, $forceTagsClosed=true, $target_charset = DEFAULT_TARGET_CHARSET, $stripRN=true, $defaultBRText=DEFAULT_BR_TEXT, $defaultSpanText=DEFAULT_SPAN_TEXT)
local/linkchecker_robot/extlib/simple_html_dom.php:101:function dump_html_tree($node, $show_attr=true, $deep=0)
local/linkchecker_robot/report.php:56:function http_code($row) {
`

**Comment by brendanheywood** [comment]
Can you please not close issues until I've reviewed them please? Pretty well none of this is correct:
- revert changes db/upgrade.php - this has broken the upgrade script
- revert extlib/simple_html_dom.php - this is a 3rd party library and we should avoid changing it
- report.php - this is a slight improvement but this isn't following the frankenstyle convention and in any case we need to change the type of the plugin anyway

Just leave this issue and #5 and we'll come back to these after everything else is resolved.

**Comment by suankan** [comment]
Reverted.
